from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1779, 861)
        MainWindow.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 0, 301, 161))
        self.groupBox_3.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.widget = QtWidgets.QWidget(self.groupBox_3)
        self.widget.setGeometry(QtCore.QRect(11, 21, 281, 50))
        self.widget.setObjectName("widget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_11.addWidget(self.label_9, 0, 0, 1, 1)
        self.input_filename = QtWidgets.QLineEdit(self.widget)
        self.input_filename.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_filename.setPlaceholderText("")
        self.input_filename.setObjectName("input_filename")
        self.gridLayout_11.addWidget(self.input_filename, 1, 0, 1, 1)
        self.browse_input = QtWidgets.QToolButton(self.widget)
        self.browse_input.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.browse_input.setObjectName("browse_input")
        self.gridLayout_11.addWidget(self.browse_input, 1, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.groupBox_3)
        self.widget1.setGeometry(QtCore.QRect(11, 73, 281, 50))
        self.widget1.setObjectName("widget1")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_7 = QtWidgets.QLabel(self.widget1)
        self.label_7.setObjectName("label_7")
        self.gridLayout_12.addWidget(self.label_7, 0, 0, 1, 1)
        self.output_filename = QtWidgets.QLineEdit(self.widget1)
        self.output_filename.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.output_filename.setPlaceholderText("")
        self.output_filename.setObjectName("output_filename")
        self.gridLayout_12.addWidget(self.output_filename, 1, 0, 1, 1)
        self.browse_output = QtWidgets.QToolButton(self.widget1)
        self.browse_output.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.browse_output.setObjectName("browse_output")
        self.gridLayout_12.addWidget(self.browse_output, 1, 1, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.groupBox_3)
        self.widget2.setGeometry(QtCore.QRect(11, 125, 281, 30))
        self.widget2.setObjectName("widget2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.load_am = QtWidgets.QPushButton(self.widget2)
        self.load_am.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.load_am.setObjectName("load_am")
        self.gridLayout_13.addWidget(self.load_am, 0, 0, 1, 1)
        self.save_am = QtWidgets.QPushButton(self.widget2)
        self.save_am.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.save_am.setObjectName("save_am")
        self.gridLayout_13.addWidget(self.save_am, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 160, 301, 671))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 20, 281, 311))
        self.groupBox_6.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 20, 261, 281))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 0, 0, 1, 1)
        self.set_structure_stability = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.set_structure_stability.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.set_structure_stability.setObjectName("set_structure_stability")
        self.gridLayout_9.addWidget(self.set_structure_stability, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.pair_cycles_number_out = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.pair_cycles_number_out.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pair_cycles_number_out.setReadOnly(True)
        self.pair_cycles_number_out.setObjectName("pair_cycles_number_out")
        self.gridLayout_3.addWidget(self.pair_cycles_number_out, 0, 1, 1, 1)
        self.pair_cycles_out = QtWidgets.QListWidget(self.layoutWidget_3)
        self.pair_cycles_out.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pair_cycles_out.setObjectName("pair_cycles_out")
        self.gridLayout_3.addWidget(self.pair_cycles_out, 1, 0, 1, 2)
        self.gridLayout_10.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 340, 281, 281))
        self.groupBox_5.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 20, 261, 251))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label = QtWidgets.QLabel(self.layoutWidget_4)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.set_value_stability = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.set_value_stability.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.set_value_stability.setObjectName("set_value_stability")
        self.gridLayout_7.addWidget(self.set_value_stability, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 1, 0, 1, 1)
        self.set_perturbation_stability = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.set_perturbation_stability.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.set_perturbation_stability.setObjectName("set_perturbation_stability")
        self.gridLayout_7.addWidget(self.set_perturbation_stability, 1, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.spectral_radius_out = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.spectral_radius_out.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spectral_radius_out.setReadOnly(True)
        self.spectral_radius_out.setObjectName("spectral_radius_out")
        self.gridLayout_2.addWidget(self.spectral_radius_out, 0, 1, 1, 1)
        self.eigenvalues_out = QtWidgets.QListWidget(self.layoutWidget_4)
        self.eigenvalues_out.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.eigenvalues_out.setObjectName("eigenvalues_out")
        self.gridLayout_2.addWidget(self.eigenvalues_out, 1, 0, 1, 2)
        self.gridLayout_8.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.check_stability_button = QtWidgets.QPushButton(self.groupBox)
        self.check_stability_button.setGeometry(QtCore.QRect(10, 630, 281, 31))
        self.check_stability_button.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.check_stability_button.setObjectName("check_stability_button")
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(1140, 100, 631, 611))
        self.groupBox_10.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.groupBox_10.setObjectName("groupBox_10")
        self.x_table = QtWidgets.QTableWidget(self.groupBox_10)
        self.x_table.setGeometry(QtCore.QRect(10, 20, 611, 581))
        self.x_table.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.x_table.setObjectName("x_table")
        self.x_table.setColumnCount(0)
        self.x_table.setRowCount(0)
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setGeometry(QtCore.QRect(320, 720, 1451, 111))
        self.groupBox_9.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.groupBox_9.setObjectName("groupBox_9")
        self.q_table = QtWidgets.QTableWidget(self.groupBox_9)
        self.q_table.setGeometry(QtCore.QRect(10, 20, 1431, 81))
        self.q_table.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.q_table.setObjectName("q_table")
        self.q_table.setColumnCount(0)
        self.q_table.setRowCount(0)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(320, 100, 811, 611))
        self.groupBox_4.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.groupBox_4.setObjectName("groupBox_4")
        self.adjacency_matrix_out = QtWidgets.QTableWidget(self.groupBox_4)
        self.adjacency_matrix_out.setGeometry(QtCore.QRect(10, 20, 791, 581))
        self.adjacency_matrix_out.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.adjacency_matrix_out.setObjectName("adjacency_matrix_out")
        self.adjacency_matrix_out.setColumnCount(0)
        self.adjacency_matrix_out.setRowCount(0)
        self.plot_graph_button = QtWidgets.QPushButton(self.centralwidget)
        self.plot_graph_button.setGeometry(QtCore.QRect(320, 10, 811, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.plot_graph_button.setFont(font)
        self.plot_graph_button.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"border-radius: 15")
        self.plot_graph_button.setObjectName("plot_graph_button")
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(1150, 20, 621, 65))
        self.widget3.setObjectName("widget3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.widget3)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.im_table = QtWidgets.QRadioButton(self.widget3)
        self.im_table.setChecked(True)
        self.im_table.setObjectName("im_table")
        self.gridLayout.addWidget(self.im_table, 0, 0, 1, 1)
        self.im_graph = QtWidgets.QRadioButton(self.widget3)
        self.im_graph.setObjectName("im_graph")
        self.gridLayout.addWidget(self.im_graph, 1, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.im = QtWidgets.QPushButton(self.widget3)
        self.im.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.im.setObjectName("im")
        self.gridLayout_4.addWidget(self.im, 0, 0, 1, 1)
        self.clear_im = QtWidgets.QPushButton(self.widget3)
        self.clear_im.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.clear_im.setObjectName("clear_im")
        self.gridLayout_4.addWidget(self.clear_im, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.impulse_modeling_steps = QtWidgets.QSpinBox(self.widget3)
        self.impulse_modeling_steps.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.impulse_modeling_steps.setMinimum(1)
        self.impulse_modeling_steps.setMaximum(100)
        self.impulse_modeling_steps.setProperty("value", 5)
        self.impulse_modeling_steps.setObjectName("impulse_modeling_steps")
        self.gridLayout_5.addWidget(self.impulse_modeling_steps, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_6, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Практична робота №6"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Вхідні дані"))
        self.label_9.setText(_translate("MainWindow", "Вхідні дані:"))
        self.input_filename.setText(_translate("MainWindow", "input.xlsx"))
        self.browse_input.setText(_translate("MainWindow", "..."))
        self.label_7.setText(_translate("MainWindow", "Вихідні дані:"))
        self.output_filename.setText(_translate("MainWindow", "output.xlsx"))
        self.browse_output.setText(_translate("MainWindow", "..."))
        self.load_am.setText(_translate("MainWindow", "Завантажити"))
        self.save_am.setText(_translate("MainWindow", "Зберегти"))
        self.groupBox.setTitle(_translate("MainWindow", "Аналіз стійкості"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Структурна стійкість"))
        self.label_3.setText(_translate("MainWindow", "Система є структурно стійкою:"))
        self.label_5.setText(_translate("MainWindow", "Кількість парних циклів:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Чисельна стійкість"))
        self.label.setText(_translate("MainWindow", "Система стійка за значенням:"))
        self.label_2.setText(_translate("MainWindow", "Система стійка за збуренням:"))
        self.label_4.setText(_translate("MainWindow", "Найбільше власне число:"))
        self.check_stability_button.setText(_translate("MainWindow", "Проаналізувати стійкість"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Імпульсна модель"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Імпульс"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Матриця суміжності"))
        self.plot_graph_button.setText(_translate("MainWindow", "Граф когнітивної карти"))
        self.im_table.setText(_translate("MainWindow", "Імпульсне моделювання: чисельні результати"))
        self.im_graph.setText(_translate("MainWindow", "Імпульсне моделювання: графічні результати"))
        self.im.setText(_translate("MainWindow", "Моделювати"))
        self.clear_im.setText(_translate("MainWindow", "Очистити"))
        self.label_6.setText(_translate("MainWindow", "Кількість кроків імпульсного моделювання"))
